version: '2'

services:
    nginx:
        build: nginx
        container_name: nginx
        ports:
            - 80:80
        links:
            - php
        volumes_from:
            - php
        volumes:
            - ./logs/nginx/:/var/log/nginx
        tty: true
        restart: always

    php:
        build: php7-fpm
        container_name: php
        ports:
            - 9000:9000
        volumes:
            - ${WORKSPACE_APP_PATH}:/var/www/workspace:cached
        tty: true
        restart: always

    db:
        user: "${USER_ID}:50"
        image: mysql
        container_name: db
        command: mysqld --sql_mode=""
        ports:
            - "3306:3306"
        volumes:
            - ${MYSQL_PATH}:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
        tty: true
        restart: always

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: phpmyadmin
        volumes:
            - ${CONFIG_FILE}:/etc/phpmyadmin/config.user.inc.php
        ports:
            - "8080:80"
        links:
            - db

    elasticsearch:
        image: elasticsearch:1.7-alpine
        container_name: elasticsearch
        ports:
          - 81:80
        volumes_from:
          - php
        volumes:
          - ./.es-data/:/usr/share/elasticsearch/data
          - ./.es-config/:/usr/share/elasticsearch/config/

#    varnish:
#        image: biko2/docker-varnish
#        container_name: varnish
#        ports:
#            - "8000:80"
#        tty: true
#        environment:
#            VARNISH_BACKEND_PORT: 80
#            VARNISH_BACKEND_IP: ${VARNISH_BACKEND_IP}
#            VARNISH_PORT: 80
#            VARNISH_MEMORY: 100M

